controller_manager:
  ros__parameters:
    update_rate: 1000  # 1kHz control loop

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    effort_controller:
      type: effort_controllers/JointGroupEffortController

# Joint State Broadcaster - publishes to /joint_states
joint_state_broadcaster:
  ros__parameters:
    joints:
      - revolute_joint
      - first_pendulum_joint
      - second_pendulum_joint
    interfaces:
      - position
      - velocity

# Unified Effort Controller for all 3 joints
effort_controller:
  ros__parameters:
    joints:
      - revolute_joint
      - first_pendulum_joint
      - second_pendulum_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort